---
# dhcpd handlers/main.yml
#
# SPDX-FileCopyrightText: © 2020 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

- name: dhcpd-restart
  service:
    name: "{{ dhcpd_service }}"
    state: restarted
