---
# dhcpd molecule/default/verify.yml
#
# SPDX-FileCopyrightText: © 2020 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

- name: Verify
  hosts: all

  tasks:

  - name: Populate service facts
    service_facts:

  - name: isc-dhcp-server is running
    assert:
      that: ansible_facts.services["isc-dhcp-server.service"]["state"] == "running"
